Updated detect_machine.sh to be consistent with UFS WM.
NOAA-EMC/global-workflow-utils pull request #42
Opened 2024-01-16 21:18 UTC by HenryWinterbottom-NOAA

This PR addresses issue #41. The following is accomplished:

- the `detect_machine.sh` script is updated to be consistent with that of the UFS WM.

2024-01-24 14:51 UTC, aerorahul approved these changes
looks good.
thanks.

2024-01-25 21:11 UTC, aerorahul commented on modulefiles/gfsutils_hera.lua
> +help([[
I don't think this is needed. Instead, the other modulefiles need to be renamed to include the `COMPILER` in their name similar to the `gfsutils_hera.intel.lua` name.

2024-01-25 21:12 UTC, aerorahul requested changes
please see a comment inline

2024-01-25 22:20 UTC, WalterKolczynski-NOAA commented on ush/detect_machine.sh
> +[[ -n ${MACHINE_ID:-} ]] && return
This should probably properly be `-v MACHINE_ID`, but since the goal is to match UFS, it's fine.

2024-01-30 18:49 UTC, aerorahul approved these changes
thanks for updating the modulefiles to be consistent.

2024-01-30 19:08 UTC, merged