Build on Gaea for APP=ATM
NOAA-EMC/global-workflow-utils pull request #67
Opened 2024-04-19 15:51 UTC by DavidBurrows-NCO

# Description
Add/update module file scripts for compiling gfs_utils on Gaea-C5

  Refs #66

# Type of change
- New feature (adds functionality)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
- Clone and build on Gaea-C5

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

2024-04-19 15:57 UTC, aerorahul requested changes
I only have 1 comment that holds this PR back.
It is the same comment I had in #64

2024-04-19 15:57 UTC, aerorahul commented on modulefiles/gfsutils_common.lua
> +local bufr_ver=os.getenv("bufr_ver") or "12.0.1"
This is the only thing that makes me pause.
Do we have `bufr_ver=12.0.1` installed as part of spack-stack 1.6.0 on other RDHPCS machines that EPIC maintains?  If not, then this change will break building of gfs-utils on Hera, Orion and Hercules.
I will check on WCOSS2, but the move to bufr v12 from v11 needs to be coordinated with the DA software as well.

2024-04-22 13:40 UTC, aerorahul approved these changes
Looks good.
Thanks for adding the capability to build on Gaea.

2024-04-22 13:41 UTC, merged

2024-04-22 13:41 UTC, DavidBurrows-NCO commented on modulefiles/gfsutils_common.lua
> +local bufr_ver=os.getenv("bufr_ver") or "12.0.1"
Morning! I reverted the bufr load to v11. And I see you approved. Thanks!

2024-04-25 13:29 UTC, DavidBurrows-NCO commented
@aerorahul Morning..The epic software team got back to me yesterday and had a small correction to the gaea module file for gfs_utils..It doesn't change anything but eliminates a python version number warning message. I have committed that change and rebuilt. What's the process to correct this PR? New PR for bug fix? Reopen here? Thanks

2024-04-25 13:46 UTC, aerorahul commented
> @aerorahul Morning..The epic software team got back to me yesterday and had a small correction to the gaea module file for gfs_utils..It doesn't change anything but eliminates a python version number warning message. I have committed that change and rebuilt. What's the process to correct this PR? New PR for bug fix? Reopen here? Thanks

Yes.  A new PR with a hotfix/bugfix is generally how this is handled.

2024-04-25 13:52 UTC, DavidBurrows-NCO commented
Great. Will do. Thanks.